fix(el): Allow spaces before expression
gravitee-io/gravitee-expression-language pull request #21
Opened 2021-07-30 11:58 UTC by brasseld

Closes gravitee-io/issues#5938

2021-09-06 10:14 UTC, leleueri requested changes
the Unit Test `io.gravitee.el.spel.context.SpelTemplateEngineTest.shouldTransformJsonContent` fails since this change

2021-09-13 11:12 UTC, phiz71 requested changes

2021-09-13 11:12 UTC, phiz71 commented on src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java
> +    private static final String EXPRESSION_REGEX = "\\{(\\\\S[^#|T|(])";
As @leleueri said, due to this regex one UT fails.
I propose this one, that seems to work. 
```suggestion
    private static final String EXPRESSION_REGEX = "\\{([^#|T|(|\\s])";
```

2021-09-14 13:08 UTC, phiz71 commented on src/main/java/io/gravitee/el/spel/SpelTemplateEngine.java
> +    private static final String EXPRESSION_REGEX = "\\{(\\\\S[^#|T|(])";
@brasseld wdyt ?

2021-09-16 12:28 UTC, phiz71 approved these changes

2021-09-16 12:29 UTC, merged